### ISSUE TITLE
What is the meaning of `NotFound` field in `Result` struct ?

### ISSUE THREAD

**Issue by slash3b** [zegl/goriak#66]
Hello,

Could you please explain why there is a `NotFound` field in `Result` struct ? 
For instance I see that here https://github.com/zegl/goriak/blob/853c1d1c26fcb79ded29a53b802c60989cf46013/map_get.go#L58 
a tuple returned that consists of struct with `NotFound: true` field  and a "not found" error. 

It seems that these two are counterintuitive — if we already return NotFound error, why do we have to return ... a basically invalid `Result` ? 

Hope my question finds you well. 
Thank you!

**Comment by zegl** [comment]
Hey! That's a good question indeed.

It's been a long time since this project was created, so it's hard to remember, but it's likely because I didn't know better.

Go has much better error handling these days (since the introduction of the `errors` package). So it for sure make sense to redesign this (and probably many other instances of the same bug) to return a nil Result and a named error.

If you want to contribute, feel free to send some PRs, and we could merge it into a v4 branch where we're fixing up the API.

**Comment by slash3b** [comment]
Thank you a lot for the answer! 
Sorry, I'm not sure I can not contribute a fix right now.
